### ISSUE TITLE
Scandinavian characters (äåö)

### ISSUE THREAD

**Issue by talakoski** [savikko/smarthome#1]
Hi,

Thanks for your repo, good collection of configuration examples!

I was looking your e-paper configs and noticed the lack of **äåö** characters.  I have had success of adding them by defining "glyphs" for each font which uses them, eg.

```
font:
  - file: 'Roboto-Medium.ttf'
    id: sm_font
    size: 20
    glyphs: "!\"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz\u00C4\u00C5\u00D6\u00E4\u00E5\u00F6"  # = default + ÄÅÖäåö
```
